variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE:latest

stages:
  - build
#  - test  до лучших времен
  - deploy
  - logs

.before script docker registry login: &before-script-docker-registry-login
  - mkdir ~/.docker
  - cat $CR_CONFIG > ~/.docker/config.json

build:
  stage: build
  image: docker:latest
  before_script:
    - *before-script-docker-registry-login
  script:
    - docker build -t $TAG_LATEST .
    - docker push $TAG_LATEST
  when: manual
  only:
    - main

deploy:
  stage: deploy
  image: hub.66bit.ru/shared/stk8s:1.26.2
  script:
    - cd ci
    - kubectl delete -f deployment.yaml
    - kubectl apply -f deployment.yaml
    - kubectl apply -f persistent.yaml
  when: manual
  only:
    - main

logs:
  stage: logs
  image: hub.66bit.ru/shared/stk8s:1.26.2
  script:
    - kubectl logs -n coderev deploy/coderev-deployment --timestamps --since=1h
  when: manual
  only:
    - main